### ISSUE TITLE
Show slide-out cart on clicking cart icon

### ISSUE THREAD

**Issue by Maxou82** [vphat28/horizontal-slide-out-cart-for-woocommerce#1]
Hi, great plugin, it works beautifully!
I was wondering if there was a way to make it work on clicking buttons othe than "add to cart".
For instance when clicking on the cart icon...

Thanks a lot for your help!

**Comment by vphat28** [comment]
this isn't quite a general function and I don't think it will be available in short future. Maybe you can custom it try to  modify woocommerce template file and add in another button

thanks for your report
