### ISSUE TITLE
Add to cart button of cross sells products not working.

### ISSUE THREAD

**Issue by pratyaych** [vphat28/horizontal-slide-out-cart-for-woocommerce#2]
Hi,
![cross-sell](https://cloud.githubusercontent.com/assets/24809468/21521801/161f17d2-cd26-11e6-9433-7515e7652c2f.png)

I am using your plugin, it's amazing. But I've an issue. Then add to cart button of the cross sell products in slide out panel, is not working. Can you please take a look into this ? 

Wordpress version: **4.7**
Woocommerce version: **2.6.11**

Thanks & regards
Pratyay.

**Comment by pratyaych** [comment]
Hi, any progress on this ? I am waiting for it.

**Comment by vphat28** [comment]
I fixed it in  a5e064d4f01b27174241d907a2a7a1857c8fa792
