### ISSUE TITLE
Not working on single product page after Woocommerce 3.0

### ISSUE THREAD

**Issue by askfranklin** [vphat28/horizontal-slide-out-cart-for-woocommerce#4]
The slide out cart is not working on single product page after updating to Woocommerce 3.0. However it works fine on product category archive and related products.

**Comment by vphat28** [comment]
please try to change the theme to some thing default with wordpress, it's still working on my end, i'm running woocommerce 3.8

**Comment by vphat28** [comment]
try change to twenty twelve theme
